# Generated by Django 3.1.5 on 2021-05-14 18:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_tr', models.CharField(max_length=100, null=True)),
                ('letter', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50000)),
                ('letter_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50000, null=True)),
                ('letter_tr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visit_num', models.PositiveIntegerField(default=0)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('coverpicture', models.ImageField(default='default.jpg', upload_to='aboutcover')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50000)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('visit_num', models.PositiveIntegerField(default=0)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('profilepicture', models.ImageField(default='profilepicture/profilepicture.png', upload_to='profilepicture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog')),
                ('user', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='commentlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
